name: complaints_sys
description: copplaints systeme app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- مكتبات أساسية للمعمارية وإدارة الحالة ---
  provider: ^6.1.2
  go_router: ^14.2.0
  dartz: ^0.10.1

  # --- مكتبات الواجهة (UI) والمساعدة ---
  flutter_screenutil: ^5.9.3
  animations: ^2.0.11
  pinput: ^4.0.0

  # --- مكتبات الشبكة والتخزين ---
  http: ^1.2.1
  flutter_secure_storage: ^9.2.4
  file_picker: ^8.0.0
  path: ^1.9.0

  # أيقونات
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # --- تعريف الأصول (Assets) ---
  assets:
    - assets/logos/logo.png # (المسار الصحيح للوغو)

  # --- تعريف الخطوط (Fonts) ---
  fonts:
    - family: Zain
      fonts:
        - asset: assets/fonts/Zain-Light.ttf
          weight: 300
        - asset: assets/fonts/Zain-Regular.ttf
          weight: 400
        - asset: assets/fonts/Zain-Bold.ttf
          weight: 700
        - asset: assets/fonts/Zain-ExtraBold.ttf
          weight: 800
